from enum import Enum


class EtherErrorCode(Enum):
    # 발생할 수 있는 Error Type을 나열하세요.
    INVALID_REQUEST = 'INVALID_REQUEST'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS'
    FORBIDDEN = 'FORBIDDEN'
    NOT_FOUND = 'NOT_FOUND'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    REQUEST_TIMEOUT = 'REQUEST_TIMEOUT'